src/JamRockApplication_v1/Models/AdminModels/Artists.cs
namespace JamRockApplication_v1.Models.AdminModels
{
    public class Artists
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string avatar { get; set; }

        public int RaveId { get; set; }

        public Rave Rave { get; set; }


    }
}

src/JamRockApplication_v1/Models/AdminViewModels/EventViewModels/AddEventViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;

namespace JamRockApplication_v1.Models.AdminViewModels.EventViewModels
{
    public class AddEventViewModel
    {
        public int ID { get; set; }

        [StringLength(150, MinimumLength = 3)]
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [StringLength(150, MinimumLength = 3)]
        [Required]
        [DataType(DataType.Text)]
        public string Location { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public DateTime eventDate { get; set; }

        [Required]
        [DataType(DataType.Upload)]
        public IFormFile eventImage { get; set; }


        [StringLength(1500, MinimumLength = 3)]
        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [DataType(DataType.Date)]
        public DateTime CreatedOn { get; set; }

        [DataType(DataType.Date)]
        public DateTime LastModified { get; set; }
    }
}

src/JamRockApplication_v1/Controllers/Admin/EventController.cs
using JamRockApplication_v1.Interfaces;
using JamRockApplication_v1.Models.AdminModels;
using JamRockApplication_v1.Models.AdminViewModels.EventViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace JamRockApplication_v1.Controllers.Admin
{
    [Authorize(Roles = "Administrator,Blogger,Staff")]
    public class EventController : Controller
    {
        private readonly IRepository<Rave> _eventRepo;
        private readonly IRepositoryManager _repoManager;
        private readonly ILogger<EventController> _logger;

        public EventController(
            IRepositoryManager repoManager,
            IRepository<Rave> eventRepo,
            ILogger<EventController> logger)
        {
            _repoManager = repoManager;
            _eventRepo = eventRepo;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var eventViewModelList = new List<DisplayEventViewModel>();
            try
            {
             
                var eventList = await _eventRepo.GetAll();

                foreach (var rave in eventList)
                {
                    var eventViewModel = new DisplayEventViewModel
                    {
                        ID = rave.ID,
                        Name = rave.Name,
                        Description = rave.Description,
                        eventImage = rave.eventImage,
                        Location = rave.Location,
                        eventDate = rave.eventDate
                    };

                    eventViewModelList.Add(eventViewModel);
                }         
            }
            catch (Exception ex)
            {
              _logger.LogError("Error:"+ex);
            }
            return View(eventViewModelList);
        }

        [HttpGet]
        public IActionResult AddEvent()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEvent(AddEventViewModel eventViewModel)
        {

            try
            {
                var imagebytes = _repoManager.UploadEventImageToCdn(eventViewModel.eventImage);

                if (string.IsNullOrEmpty(imagebytes)) return View(eventViewModel);
                var rave = new Rave
                {
                    Name = eventViewModel.Name,
                    eventImage = imagebytes,
                    Description = eventViewModel.Description,
                    Location = eventViewModel.Location,
                    CreatedOn = new DateTime(),
                    LastModified = new DateTime(),
                    eventDate = eventViewModel.eventDate
                };


                await _eventRepo.Add(rave);

                return RedirectToAction("EventDetails",new {id = rave.ID });
            }
            catch (Exception ex)
            {
                _logger.LogError("exception" + ex);
            
            }
            return View(eventViewModel);
        }

        public async Task<IActionResult> DeleteEvent(int? id)
        {
            var rave = await _eventRepo.FindById(id);

            await _eventRepo.Delete(rave);

            return RedirectToAction("Index");
        }
        
        public async Task<IActionResult> EventDetails(int id)
        {
            var Event = await _eventRepo.FindById(id);


            if(Event == null)
            {
                return NotFound();
            }
            var vm = new DisplayEventViewModel
            {
                eventImage = Event.eventImage,
                ID = Event.ID,
                Name = Event.Name,
                Location = Event.Location,
                eventDate = Event.eventDate,
                Description = Event.Description
            };




            foreach(var a in Event.Artists)
            {
                var m = new DisplayArtistViewModel
                {
                    avatar = a.avatar,
                    Name = a.Name,
                    Id = a.Id
                };


                vm.eventArtists.Add(m);
            }

            foreach(var g in Event.Gallery)
            {
                var item = new galleryItemViewModel
                {
                    Id = g.Id,
                    Image = g.Image
                };


                vm.Gallery.Add(item);
            }


            return View(vm);
        }

        [HttpGet]
        public IActionResult NewArtist(DisplayEventViewModel model)
        {
            ViewBag.rave = model.ID;

            return View("_artistView");
        }

        [HttpPost]
        public async Task<IActionResult> AddArtist(AddArtistViewModel model)
        {
            var selectedEvent = await _eventRepo.FindById(model.raveId);

            if (selectedEvent == null)
            {
                return NotFound();
            }
            else
            {
                var newArtist = new Artists
                {
                    avatar = _repoManager.UploadEventImageToCdn(model.avatar),
                    Name = model.Name
                };


                selectedEvent.Artists.Add(newArtist);

                await _eventRepo.Update(selectedEvent);
                return RedirectToAction("EventDetails", new { @id = model.raveId });
            }

        }

        public async Task<IActionResult> RemoveArtist(int? id,int rave)
        {
            var Event = await _eventRepo.FindById(rave);

            var artist = Event.Artists.Find(a => a.Id.Equals(id));


            Event.Artists.Remove(artist);

            await _eventRepo.Update(Event);

            return RedirectToAction("EventDetails", new { @id = rave });
        }

        public async Task<IActionResult> RemoveImage(int? id, int rave)
        {
            var Event = await _eventRepo.FindById(rave);

            var galleryImage = Event.Gallery.Find(a => a.Id.Equals(id));


            if (galleryImage == null) return NotFound();
            Event.Gallery.Remove(galleryImage);

            await _eventRepo.Update(Event);

            return RedirectToAction("EventDetails", new { id = rave });
        }

        [HttpPost]
        public async Task<IActionResult> AddImages(IFormCollection files)
        {
            if(files == null)
            {
                return BadRequest(new { error = "Files are empty" });
            }
            try
            {
                var selected = await _eventRepo.FindById(Convert.ToInt32(files["event"]));

                foreach(var image in files.Files)
                {
                    var item = new galleryItem {Image = _repoManager.UploadGalleryImageToCdn(image)};


                    selected.Gallery.Add(item);
                }

                await _eventRepo.Update(selected);

                return Ok(new { result = "Gallery Created"});
            }
            catch (Exception ex)
            {
                _logger.LogError("Error creating gallery", ex.ToString());
                return BadRequest(new { error = "Error creating gallery"});
            }
        }

        public async Task<IActionResult> UpdateEventName(int? id,string name)
        {
            try
            {
                if (id != null)
                {
                    var Event = await _eventRepo.FindById(id);

                    if (Event != null)
                    {
                        Event.Name = name;

                        await _eventRepo.Update(Event);

                        return Ok(new { result = "Ok" });
                    }

                }
                return BadRequest();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error", ex.ToString());
                return BadRequest();
            }

        }

        public async Task<IActionResult> UpdateEventLocation(int? id, string location)
        {
            try
            {
                if (id != null)
                {
                    var Event = await _eventRepo.FindById(id);

                    if (Event != null)
                    {
                        Event.Location = location;
                        await _eventRepo.Update(Event);
                        return Ok(new { result = "Ok" });
                    }

                }
                return BadRequest();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error", ex.ToString());
                return BadRequest();
            }

        }

        public async Task<IActionResult> UpdateEventDescription(int? id, string description)
        {
            try
            {
                if (id != null)
                {
                    var Event = await _eventRepo.FindById(id);

                    if (Event != null)
                    {
                        Event.Description = description;
                        await _eventRepo.Update(Event);
                        return Ok(new { result = "Ok" });
                    }

                }
                return BadRequest();
            }
            catch (Exception ex)
            {
                _logger.LogError("Error", ex.ToString());
                return BadRequest();
            }

        }

        public async Task<IActionResult> UpdateEventDate(int? id, DateTime date)
        {
            try
            {
                if (id != null)
                {
                    var Event = await _eventRepo.FindById(id);

                    if (Event != null)
                    {
                        Event.eventDate = date;
                        await _eventRepo.Update(Event);

src/JamRockApplication_v1/Views/Event/AddEvent.cshtml
@model JamRockApplication_v1.Models.AdminViewModels.EventViewModels.AddEventViewModel
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container-fluid">
    <br />
    <div class="row">
        <form asp-action="AddEvent" enctype="multipart/form-data">
            <div class="col-md-4">
                <div class="card card-profile">
                    <div class="card-avatar">
                        <a>
                            <img class="img-responsive" src="~/images/download.png" id="imgPreview" style="height:200px;width:200px;" alt="placeholder"/>
                        </a>
                    </div>
                    <div class="content">
                        <h6 class="category text-gray">Event Image</h6>
                        <h4 class="card-title">Please Upload Your event image here</h4>
                        <div class="form-group">
                            <label class="btn btn-primary">Select Image</label>
                            <input type="file" asp-for="eventImage" onchange="previewFile(this)" accept="image/*" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title text-center">Event Information</h4>
                    </div>
                    <div class="card-content">

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                        <label asp-for="Name" class="control-label"></label>
                                        <input asp-for="Name" class="form-control" type="text"/>
                                        <span asp-validation-for="Name" class="text-danger"></span>                                   
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div>
                                        <label asp-for="eventDate" class="control-label"></label>
                                        <input asp-for="eventDate" class="form-control" type="date" />
                                        <span asp-validation-for="eventDate" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <div>
                                        <label asp-for="Location" class="control-label"></label>
                                        <input asp-for="Location" class="form-control" type="text"/>
                                        <span asp-validation-for="Location" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div>
                                    <label asp-for="Description" class="control-label"></label>
                                    <textarea asp-for="Description" class="form-control" rows="3" type="text"></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary pull-right">Add Event</button>
                        <div class="clearfix"></div>

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/JamRockApplication_v1/Views/Event/Index.cshtml
@model IEnumerable<JamRockApplication_v1.Models.AdminViewModels.EventViewModels.DisplayEventViewModel>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
    <a class="btn btn-primary" asp-controller="Event" asp-action="AddEvent">Add New Event</a>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Events Table</h4>
            </div>
            <div class="card-content table-responsive">
                @if (Model == null)
                {
                    <h3>No Events In The Database</h3>

                }
                else
                {
                    <table class="table" id="dataTable">
                        <thead class="text-primary">
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.eventImage)</th>
                                <th>@Html.DisplayNameFor(model => model.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Location)</th>
                                <th>@Html.DisplayNameFor(model => model.eventDate)</th>
                            </tr>                
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><img class="img-responsive img-thumbnail" style="width:50px;height:50px;" src="@item.eventImage" /></td>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Location)</td>
                                    <td>@Html.DisplayFor(modelItem => item.eventDate)</td>
                                    <td>
                                        <a asp-action="DeleteEvent" asp-route-id="@item.ID">Delete <i class="fa fa-trash-o" aria-hidden="true"></i>|</a>
                                        <a asp-action="EventDetails" asp-route-id="@item.ID">Manage <i class="fa fa-plus" aria-hidden="true"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>

                }
            </div>
        </div>
    </div>
</div>

src/JamRockApplication_v1/Views/Event/_artistView.cshtml
@model JamRockApplication_v1.Models.AdminViewModels.EventViewModels.AddArtistViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
    <form asp-action="AddArtist" enctype="multipart/form-data">
        <input hidden asp-for="raveId" value="@ViewBag.rave"/>
        <div class="col-md-4">
            <div class="card card-profile">
                <div class="card-avatar">
                    <a>
                        <img class="img-responsive" src="~/images/download.png" id="imgPreview" style="height:200px;width:200px;" alt="placeholder"/>
                    </a>
                </div>
                <div class="content">
                    <h6 class="category text-gray">Artist Image</h6>
                    <h4 class="card-title">Please Upload image here</h4>
                    <div class="form-group">
                        <label for="exampleInputFile" class="btn btn-primary">Select Image</label>
                        <input type="file" asp-for="avatar" onchange="previewFile(this)" accept="image/*" />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" data-background-color="purple">
                    <h4 class="title text-center">Artist Information</h4>
                </div>
                <div class="card-content">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" type="text" />
                                <span asp-validation-for="Name" class="text-danger" />
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right">Add Artist</button>
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>
    </form>
</div>

src/JamRockApplication_v1/Views/Event/eventDetails.cshtml
@model JamRockApplication_v1.Models.AdminViewModels.EventViewModels.DisplayEventViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = Model.Name + " Details";
}

<div class="container">
    <div class="row">
        <div class="col-md-5">
            <img class="img-responsive img-thumbnail" style="width:200px;height:200px;" src="@Model.eventImage" id="imgPreviewEdit" />
            <div class="form-group">
                <label class="btn btn-primary">Select New Image</label>
                <input type="file" onchange="EditpreviewFile(this)" accept="image/*" />
            </div>
            <button class="btn btn-danger" onclick="updateEventImage(@Model.ID)">Change Image</button>
        </div>
        <div class="col-md-7 table-responsive">
            <table class="table table-bordered table-hover">
                <tbody>
                    <tr>
                        <td>
                            Event Name
                        </td>
                        <td>
                            <input value="@Model.Name" id="eventName" type="text" />
                        </td>
                        <td>
                            <button class="btn btn-warning" onclick="updateEventName(@Model.ID)">Update</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Event Location
                        </td>
                        <td>
                            <input value="@Model.Location" id="eventLocation" type="text" />
                        </td>
                        <td>
                            <button class="btn btn-warning" onclick="updateEventLocation(@Model.ID)">Update</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Event Description
                        </td>
                        <td>
                            <input value="@Model.Description" id="eventDescription" type="text" />
                        </td>
                        <td>
                            <button class="btn btn-warning" onclick="updateEventDescription(@Model.ID)">Update</button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Event Date
                        </td>
                        <td>
                            <input type="date" id="eventDate" placeholder="@Model.eventDate.ToShortDateString()"/>
                        </td>
                        <td>
                            <button class="btn btn-warning" onclick="updateEventDate(@Model.ID)">Update</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <hr />
    <br />
    <h3>Artist Line Up</h3>
    <a asp-action="NewArtist" asp-route-id="@Model.ID" class="btn btn-success">Add New Artist</a>
    <hr />
    <div class="row">
        @foreach (var item in Model.eventArtists)
        {
        <div class="col-md-3">
            <img class="img-responsive img-thumbnail" style="width:150px;height:150px;" src="@item.avatar" alt="@item.Name image" />
            <h5>@item.Name</h5>
            <a class="btn btn-danger" asp-action="RemoveArtist" asp-route-id="@item.Id" asp-route-rave="@Model.ID">Remove</a>
        </div>
        }
    </div>
    <hr />
    <div class="row">
        <h2>Gallery</h2>
        <div class="btn btn-primary btn-sm">

            <span>Select Images to Upload</span>
            <input type="file" multiple id="eventImages" onchange="setImages(this)">
        </div>
        <a onclick="startUpload(@Model.ID)" class="btn btn-info">Upload Images</a>
        <hr/>
        @foreach (var item in Model.Gallery)
        {
        <div class="col-md-2">
            <img class="img-responsive img-thumbnail" style="width:100px;height:100px;" src="@item.Image" alt="gallery item" />
            <a class="btn btn-danger" asp-action="RemoveImage" asp-route-id="@item.Id" asp-route-rave="@Model.ID">Remove</a>
        </div>
        }
    </div>
</div>