src/JamRockApplication_v1/Models/AdminModels/Order.cs
using System.Collections.Generic;

namespace JamRockApplication_v1.Models.AdminModels
{
    public class Order
    {
        public Order()
        {
                OrderItems = new List<cartItem>();
            Status = "Pending";
        }
        public int Id { get; set; }

        public List<cartItem> OrderItems { get; set; }

        public string DeliveryType { get; set; }

        public int CustomerId { get; set; }

        public Customer Customer { get; set; }

        public string Status { get; set; }
    }
}

src/JamRockApplication_v1/Models/AdminModels/Product.cs
using System;
using System.Collections.Generic;

namespace JamRockApplication_v1.Models.AdminModels
{
    public class Product
    {
        public Product()
        {
                ColorSizes = new List<ColorSize>();
        }
        public int ID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Gender { get; set; }
        public double Price { get; set; }
        public int Quantity { get; set; }
        public int QuantitySold { get; set; }
        public string Description { get; set; }
        public string productImageByteArray { get; set; }
        public DateTime createdOn { get; set; } = DateTime.Now;

        public List<ColorSize> ColorSizes { get; set; }
    }
}

src/JamRockApplication_v1/Models/AdminViewModels/ProductViewModels/AddProductViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;

namespace JamRockApplication_v1.Models.AdminViewModels.ProductViewModels
{
    public class AddProductViewModel
    {
        public int ID { get; set; }

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Category { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Gender { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        public double Price { get; set; }

        [Required]
        public int Quantity { get; set; }

        [StringLength(200, MinimumLength = 3)]
        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Upload)]
        public IFormFile productImage { get; set; }
    }
}

src/JamRockApplication_v1/Controllers/Admin/ProductController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using JamRockApplication_v1.Interfaces;
using JamRockApplication_v1.Models.AdminModels;
using JamRockApplication_v1.Models.AdminViewModels.ProductViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;


// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace JamRockApplication_v1.Controllers.Admin
{
    [Authorize(Roles = "Administrator,Blogger,Staff")]
    public class ProductController : Controller
    {
        private readonly IRepository<Product> _productRepo;
        private readonly IRepositoryManager _repoManager;
        private readonly ILogger<ProductController> _logger;
        private readonly IRepository<Order> _orderRepo;

        public ProductController(IRepository<Product> productRepo,
            IRepositoryManager repoManager,
            IRepository<Rave> eventRepo,
            ILogger<ProductController> logger,
            IRepository<Customer> customerRepo,
            IRepository<Order> orderRepo)
        {
            _productRepo = productRepo;
            _repoManager = repoManager;
            _logger = logger;
            _orderRepo = orderRepo;
        }



        [HttpGet]
        public async Task<IActionResult> Products()
        {
            var productViewModelList = new List<DisplayProductViewModel>();
            try
            {
                var productList = await _productRepo.GetAll();

                foreach (var product in productList)
                {
                    var productViewModel = new DisplayProductViewModel
                    {
                        ID = product.ID,
                        Name = product.Name,
                        Price = product.Price,
                        Quantity = product.Quantity,
                        Description = product.Description,
                        Category = product.Category,
                        productImage = product.productImageByteArray,
                        SoldQuantity = product.QuantitySold,
                        remainingQuantity = product.Quantity - product.QuantitySold
                    };

                    productViewModelList.Add(productViewModel);
                }

            }
            catch (Exception e)
            {
                _logger.LogError("Error Getting List of Products:" +e);
            }
          
            return View(productViewModelList);
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductViewModel productViewModel)
        {

            try
            {
                var imagebytes = _repoManager.UploadProductImageToCdn(productViewModel.productImage);

                if (string.IsNullOrEmpty(imagebytes)) return View(productViewModel);
                var product = new Product
                {
                    Name = productViewModel.Name,
                    Price = productViewModel.Price,
                    productImageByteArray = imagebytes,
                    Category = productViewModel.Category,
                    Description = productViewModel.Description,
                    Gender = productViewModel.Gender
                };


                await _productRepo.Add(product);

                return RedirectToAction("UpdateProduct", new { id = product.ID});
            }
            catch (Exception ex)
            {
                _logger.LogError("exception" + ex);
            }
            return View(productViewModel);
        }

        public async Task<IActionResult> AddColorSize(int? id, ColorSize model)
        {
            if (id == null) return BadRequest();
            var product = await _productRepo.FindById(id);

            var cs = product.ColorSizes.Find(c => c.Color.Equals(model.Color) && c.Size.Equals(model.Size));

            if (cs != null)
            {
                cs.Quantity += model.Quantity;
                cs.QuantityLeft += model.Quantity;
            }
            else
            {
                model.QuantityLeft = model.Quantity;
                product.ColorSizes.Add(model);
            }

            product.Quantity = product.Quantity + model.Quantity;

            await _productRepo.Update(product);

            return Ok(new {result = "ok"});
        }

        public async Task<IActionResult> DeleteProduct(DisplayProductViewModel displayProductViewModel)
        {
            if (displayProductViewModel == null)
            {
                return NotFound();
            }

            try
            {
                var product = await _productRepo.FindById(displayProductViewModel.ID);

                if (product != null)
                {
                    await _productRepo.Delete(product);
                }
            }
            catch (Exception ex)
            {

                _logger.LogError("exception" + ex);
            }
            return RedirectToAction("Products");

        }

        public async Task<IActionResult> DeleteMultiple(int[] selected)
        {
            if (selected == null)
            {
                return NotFound();
            }

            try
            {
                foreach (var s in selected)
                {
                    var product = await _productRepo.FindById(s);

                    if (product != null)
                    {
                        await _productRepo.Delete(product);
                    }
                }
                return RedirectToAction("Products");
            }
            catch (Exception ex)
            {

                _logger.LogError("exception" + ex);
            }

            return RedirectToAction("Products");

        }

        public async Task<IActionResult> Orders()
        {
            var orders = new List<Order>();
            try
            {
                var orderList = await _orderRepo.GetAll();

                foreach (var item in orderList)
                {
                    orders.Add(item);
                }
            }
            catch (Exception e)
            {
                _logger.LogError("Error Getting Orders:"+e);
            }
           

            return View(orders);
        }

        public async Task<IActionResult> OrderDetails(int? id)
        {
            try
            {
                if (id == null) return RedirectToAction("Orders");
                var order = await _orderRepo.FindById(id);

                return View(order);
            }
            catch (Exception ex)
            {
                _logger.LogError("Error"+ex);
                return RedirectToAction("Orders");
            }
     
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var product = await _productRepo.FindById(id);

                var productViewModel = new DisplayProductViewModel
                {
                    ID = product.ID,
                    Name = product.Name,
                    Price = product.Price,
                    Quantity = product.Quantity,
                    Category = product.Category,
                    Description = product.Description,
                    Gender = product.Gender,
                    productImage = product.productImageByteArray,
                    ColorSizes = product.ColorSizes
                };

                return View(productViewModel);
            }
            catch (Exception)
            {
                return RedirectToAction("Products");
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductName(int id, string name)
        {
            var product = await _productRepo.FindById(id);


            if(product == null)
            {
                return BadRequest(new { error="Error"});
            }
            product.Name = name;

            await _productRepo.Update(product);

            return Ok(new {result = "Ok" });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductQuantity(int id, int quantity)
        {
            var product = await _productRepo.FindById(id);


            if (product == null)
            {
                return BadRequest(new { error = "Error" });
            }
            product.Quantity = product.Quantity + quantity;

            await _productRepo.Update(product);

            return Ok(new { result = "Ok" });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductDescription(int id, string description)
        {
            var product = await _productRepo.FindById(id);


            if (product == null)
            {
                return BadRequest(new { error = "Error" });
            }
            product.Description = description;

            await _productRepo.Update(product);

            return Ok(new { result = "Ok" });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductGender(int id, string gender)
        {
            var product = await _productRepo.FindById(id);


            if (product == null)
            {
                return BadRequest(new { error = "Error" });
            }
            product.Gender = gender;

            await _productRepo.Update(product);

            return Ok(new { result = "Ok" });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProductCategory(int id, string category)
        {
            var product = await _productRepo.FindById(id);


            if (product == null)
            {

src/JamRockApplication_v1/Views/Product/AddProduct.cshtml
@model JamRockApplication_v1.Models.AdminViewModels.ProductViewModels.AddProductViewModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Add Product";
}


<div class="container-fluid">
    <div class="row">
        <form asp-action="AddProduct" enctype="multipart/form-data">
            <div class="col-md-4">
                <div class="card card-profile">
                    <div class="card-avatar">
                        <a>
                            <img class="img-responsive" src="~/images/download.png" id="imgPreview" style="height:200px;width:200px;" alt="placeholder"/>
                        </a>
                    </div>
                    <div class="content">
                        <h6 class="category text-gray">Event Image</h6>
                        <h4 class="card-title">Please Upload Your event image here</h4>
                        <div class="form-group">
                            <label for="exampleInputFile" class="btn btn-primary">Select Image</label>
                            <input type="file" asp-for="productImage" onchange="previewFile(this)" accept="image/*" required/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header" data-background-color="purple">
                        <h4 class="title text-center">Product Information</h4>
                    </div>
                    <div class="card-content">

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group label-floating">
                                    <label asp-for="Name" class="col-md-2 control-label"></label>
                                    <input asp-for="Name" class="form-control" required type="text"/>
                                    <span asp-validation-for="Name" class="text-danger" />
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group label-floating">
                                    <label asp-for="Price" class="col-md-2 control-label"></label>
                                    <input asp-for="Price" class="form-control" required type="number"/>
                                    <span asp-validation-for="Price" class="text-danger" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <select class="form-control" asp-for="Gender" required>
                                    <option selected disabled>Choose Gender</option>
                                    <option value="Men">Men</option>
                                    <option value="Women">Women</option>
                                    <option value="Both">Both</option>
                                </select>
                                <span asp-validation-for="Gender" class="text-danger" />
                            </div>
                            <div class="col-md-6">
                                <select class="form-control" asp-for="Category" required>
                                    <option selected disabled>Choose Category</option>
                                    <option value="T-Shirt">T-Shirt</option>
                                    <option value="Polo-Shirt">Polo Shirt</option>
                                    <option value="Tank-Top">Tank Top</option>
                                    <option value="Trucker-Caps">Trucker Caps</option>
                                    <option value="BaseBall-Caps">BaseBall-Caps</option>
                                    <option value="Snap-Back">Snap-Back</option>
                                    <option value="Accessory">Accessory</option>
                                </select>
                                <span asp-validation-for="Category" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group label-floating">
                                    <label asp-for="Description" class="col-md-2 control-label"></label>
                                    <textarea asp-for="Description" class="form-control" rows="3" required type="text"></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary pull-right">Add Product</button>
                        <div class="clearfix"></div>

                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/JamRockApplication_v1/Views/Product/ColorAndSize.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/JamRockApplication_v1/Views/Product/OrderDetails.cshtml
@model JamRockApplication_v1.Models.AdminModels.Order
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Order Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="yellow">
                <h4 class="title">Orders Details</h4>
            </div>
            <div class="card-content table-responsive">
                @if (Model == null)
                {
                    <h2>No Orders in the Database</h2>

                }
                else
                {
                    <table class="table">
                        <thead class="text-primary">
                        <tr>
                            <th>Product Name</th>
                            <th>Product Size</th>
                            <th>Product Color</th>
                            <th>Product Quantity</th>
                            <th>Product Price</th>
                        </tr>
                        </thead>
                        <tbody id="tb">
                        @foreach (var item in Model.OrderItems)
                        {
                            <tr>
                                <td>
                                    @item.ProductName
                                </td>
                                <td>@item.ProductSize</td>
                                <td>@item.ProductColor</td>
                                <td>@item.ProductQuantity</td>
                                <td>@item.ProductPrice</td>                          
                            </tr>
                        }
                        </tbody>

                    </table>

                }

            </div>
        </div>
    </div>
</div>

src/JamRockApplication_v1/Views/Product/Orders.cshtml
@model IEnumerable<JamRockApplication_v1.Models.AdminModels.Order>
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Orders";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Shop Orders</h4>
            </div>
            <div class="card-content table-responsive">
                @if (Model == null)
                {
                    <h2>No Orders in the Database</h2>

                }
                else
                {
                    <table class="table" id="dataTable">
                        <thead class="text-primary">
                            <tr>
                                <th>Customer Name</th>
                                <th>Customer Email</th>
                                <th>Phone Number</th>
                                <th>Delivery Type</th>
                                <th>Status</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="tb">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.Customer.Name
                                    </td>
                                    <td>@item.Customer.Email</td>
                                    <td>@item.Customer.Phone</td>
                                    <td>@item.DeliveryType</td>
                                    <td>@item.Status</td>
                                    <td>
                                        <a asp-action="OrderDetails" asp-route-id="@item.Id">details</a>
                                    </td>
                                    <td>
                                        @if (item.Status.Equals("Complete"))
                                        {
                                            <a class="btn btn-info">Completed</a>
                                        }
                                        else
                                        {
                                            <a asp-action="updateProductStatus" asp-route-id="@item.Id" class="btn btn-success">Mark As Completed</a> 
                                        }
                                        
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>

                }

            </div>
        </div>
    </div>
</div>

src/JamRockApplication_v1/Views/Product/Products.cshtml
@model IEnumerable<JamRockApplication_v1.Models.AdminViewModels.ProductViewModels.DisplayProductViewModel>
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Producs";
}

<div class="row">
    <a class="btn btn-primary" asp-controller="Product" asp-action="AddProduct">Add New Product</a>
    <a class="btn btn-primary" onclick="deleteSelected()">Delete Selected Products</a>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Products List</h4>
            </div>
            <div class="card-content table-responsive">
                @if (Model == null)
                {
                    <h2>No Products in the Database</h2>

                }
                else
                {
                    <table class="table" id="dataTable">
                        <thead class="text-primary">
                            <tr>
                                <th></th>
                                <th>@Html.DisplayNameFor(model => model.productImage)</th>
                                <th>@Html.DisplayNameFor(model => model.Name)</th>
                                <th>@Html.DisplayNameFor(model => model.Price)</th>
                                <th>@Html.DisplayNameFor(model => model.Category)</th>
                                <th>@Html.DisplayNameFor(model => model.Quantity)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="tb">
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><input type="checkbox" id="@item.ID" /></td>
                                    <td>
                                        <img class="img-responsive img-thumbnail" style="width:50px;height:50px;" src="@item.productImage" />
                                    </td>
                                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Price)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Category)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                                    <td>
                                        <a asp-action="UpdateProduct" asp-route-id="@item.ID"><i class="fa fa-pencil" aria-hidden="true"></i>/---/</a>
                                        <a asp-action="DeleteProduct" asp-route-id="@item.ID"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>

                }

            </div>
        </div>
    </div>
</div>