src/JamRockApplication_v1/Models/AdminModels/Customer.cs
using System.ComponentModel.DataAnnotations;

namespace JamRockApplication_v1.Models.AdminModels
{
    public class Customer
    {
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Address { get; set; }


        [Required]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

    }
}

src/JamRockApplication_v1/Controllers/Admin/UsersController.cs
using System;
using JamRockApplication_v1.Interfaces;
using JamRockApplication_v1.Models.AccountViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JamRockApplication_v1.Models.AdminModels;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace JamRockApplication_v1.Controllers.Admin
{
    [Authorize(Roles = "Administrator,Blogger,Staff")]
    public class UsersController : Controller
    {
        private readonly ILogger<UsersController> _logger;
        private readonly IRepository<Customer> _customerRepo;
        private readonly IUserManager<RegisterViewModel> _userService;

        public UsersController(IHostingEnvironment environment,
            ILogger<UsersController> logger,
            IRepository<Customer> customerRepo,
            IUserManager<RegisterViewModel> userService)
        {
            _logger = logger;
            _customerRepo = customerRepo;
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Customers()
        {
            var displayList = new List<Customer>();

            try
            {
                var result = await _customerRepo.GetAll();

                displayList = result.GroupBy(u => u.Email).Select(g => g.First()).ToList();

                return View(displayList);
            }
            catch (Exception ex)
            {

                _logger.LogError("Error:"+ex);
                return View(displayList);
            }           
        }


        [HttpGet]
        public IActionResult NewUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> NewUser(RegisterViewModel model, string returnUrl = null)
        {
            try
            {
                if (!ModelState.IsValid) return View();
                var status = await _userService.Registration(model);
                ViewBag.status = status ? "Successful, New User Created" : "Error, User Not Created";
                return View();
            }
            catch (Exception e)
            {
                _logger.LogError("Error creating new user"+e);
                ViewBag.status = "Exception Error";
                return View();
            }
        }
    }
}

src/JamRockApplication_v1/Views/Users/Customers.cshtml
@model IEnumerable<JamRockApplication_v1.Models.AdminModels.Customer>
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "Customers";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="yellow">
                <h4 class="title">Orders Management</h4>
            </div>
            <div class="card-content table-responsive">
                @if (Model == null)
                {
                    <h2>No Customers in the Database</h2>

                }
                else
                {
                    <table class="table" id="dataTable">
                        <thead class="text-primary">
                        <tr>
                            <th>Customer Name</th>
                            <th>Customer Email</th>
                            <th>Phone Number</th>
                            <th>Address</th>
                        </tr>
                        </thead>
                        <tbody id="tb">
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Name
                                </td>
                                <td>@item.Email</td>
                                <td>@item.Phone</td>
                                <td>@item.Address</td>
                            </tr>
                        }
                        </tbody>

                    </table>

                }

            </div>
        </div>
    </div>
</div>

src/JamRockApplication_v1/Views/Users/NewUser.cshtml
@model RegisterViewModel
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewData["Title"] = "New User";
}
<div class="container-fluid">
    <div class="row flex-center">
        @if (ViewBag.status != null)
        {
            <div class="alert alert-info">
                <button class="close" type="button">X</button>
                <span>@ViewBag.status</span>
            </div> 
        }

        <div class="col-md-6 content-center">
            <div class="card ">
                <form asp-controller="Users" asp-action="NewUser" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

                    <div class="card-header" data-background-color="purple">
                        <h4 class="title text-center">Create New User</h4>
                    </div>

                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="card-content">
                        <div class="input-group form-group-no-border input-lg">
                            <span class="input-group-addon">
                            </span>
                            <input asp-for="Name" class="form-control" placeholder="Full Name" type="text"/>

                        </div>
                        <div class="input-group form-group-no-border input-lg">
                            <span class="input-group-addon">
                            </span>
                            <input asp-for="Email" class="form-control" placeholder="Email" type="email"/>

                        </div>
                        <div class="input-group form-group-no-border input-lg">
                            <span class="input-group-addon">
                            </span>
                            <input asp-for="Password" class="form-control" placeholder="Password" type="password"/>

                        </div>
                        <div class="input-group form-group-no-border input-lg">
                            <span class="input-group-addon">
                            </span>
                            <input asp-for="ConfirmPassword" class="form-control" placeholder="Confirm Password" type="password"/>

                        </div>
                        <div class="input-group form-group-no-border input-lg">
                            <select class="form-control" asp-for="Role">
                                <option selected disabled>Choose Role</option>
                                <option value="Administrator">Administrator</option>
                                <option value="Staff">Shop Staff</option>
                                <option value="Blogger">Blog Staff</option>
                            </select>
                            <span asp-validation-for="Role" class="text-danger"/>

                        </div>
                    </div>
                    <div class="footer text-center">
                        <button type="submit" class="btn btn-primary btn-round btn-lg">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}