src/JamRockApplication_v1/Controllers/Admin/AdminController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using JamRockApplication_v1.Interfaces;
using JamRockApplication_v1.Models.AdminModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace JamRockApplication_v1.Controllers.Admin
{
    [Authorize(Roles = "Administrator,Blogger,Staff")]
    public class AdminController : Controller
    {
        private readonly ILogger<AdminController> _logger;
        private readonly IRepository<Post> _postRepo;
        private readonly IRepository<Rave> _eventRepo;
        private readonly IRepository<Product> _productRepo;
        private readonly IRepository<Order> _orderRepo;
        private readonly IRepository<Customer> _customerRepo;


        public AdminController(ILogger<AdminController> logger, IRepository<Post> postRepo, IRepository<Rave> eventRepo,
            IRepository<Product> productRepo, IRepository<Order> orderRepo, IRepository<Customer> customerRepo)
        {
            _logger = logger;
            _postRepo = postRepo;
            _eventRepo = eventRepo;
            _productRepo = productRepo;
            _orderRepo = orderRepo;
            _customerRepo = customerRepo;
        }
        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var revenue = 0.0;
            var productsSold = 0;


            try
            {
                var orderList = await _orderRepo.GetAll();

                foreach (var item in orderList)
                {
                    //get total revenue 
                    revenue = item.OrderItems.Aggregate(revenue, (current, row) => row.Amount + current);

                    //get quantity of total products sold
                    productsSold =
                        item.OrderItems.Aggregate(productsSold, (current, row) => row.ProductQuantity + current);   
                    
                                   
                }

                var ordersCompleted = orderList.Count(u => u.Status.Equals("Complete"));

                var ordersPending = orderList.Count(u => u.Status.Equals("Pending"));

                var blogList = await _postRepo.GetAll();
                var posts = blogList.Count();

                var customerList = await _customerRepo.GetAll();
                var customers = customerList.GroupBy(c => c.Email).Count();
                
                ViewBag.revenue = revenue;
                ViewBag.productsSold = productsSold;
                ViewBag.posts = posts;
                ViewBag.customers = customers;
                ViewBag.ordersTotal = orderList.Count();
                ViewBag.ordersCompleted = ordersCompleted;
                ViewBag.ordersPending = ordersPending;


                ViewBag.lastUpdated = DateTime.Now.ToLongTimeString();
            }
            catch (Exception e)
            {
                _logger.LogError("Error in index page of admin:" + e);
            }      
            return View();
        }

        public IActionResult Documentation()
        {
            return View();
        }

    }
}

src/JamRockApplication_v1/Controllers/Shop/ShopController.cs
using JamRockApplication_v1.Interfaces;
using JamRockApplication_v1.Models.AdminModels;
using JamRockApplication_v1.Models.AdminViewModels.CartViewModels;
using JamRockApplication_v1.Models.AdminViewModels.ProductViewModels;
using JamRockApplication_v1.Models.ShopViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using JamRockApplication_v1.Services;
using Microsoft.AspNetCore.Hosting;
using RazorEngine.Templating;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace JamRockApplication_v1.Controllers.Shop
{
    public class ShopController : Controller
    {
        private readonly IRepository<Product> _productRepo;
        private readonly IRepository<Cart> _cartRepo;
        private readonly IRepository<Order> _orderRepo;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<ShopController> _logger;
        private readonly IEmailSender _msgService;
        private ISession Session => _httpContextAccessor.HttpContext.Session;
        public const string CartSessionKey = "Id";
        private readonly IHostingEnvironment _hostingEnvironment;

        public ShopController(IRepository<Product> productRepo,
         IRepositoryManager repoManager,
         IHttpContextAccessor httpContextAccessor,
         IRepository<Cart> cartRepo,
            IRepository<Customer> customerRepo,
            IRepository<Order> orderRepo,
        IEmailSender msgService,
         ILogger<ShopController> logger,
            IHostingEnvironment hostingEnvironment)
        {
            _productRepo = productRepo;
            _httpContextAccessor = httpContextAccessor;
            _cartRepo = cartRepo;
            _logger = logger;
            _msgService = msgService;
            _orderRepo = orderRepo;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var featuredProducts = await _productRepo.Findfeatured();
            var newProducts = await _productRepo.FindNewest();
            var randomProducts = await _productRepo.FindRandom();
            var topProducts = await _productRepo.FindTop();

            var shvm = new shopHomeViewModel();

            try
            {
                foreach (var p in newProducts)
                {
                    var model = new newProducts
                    {
                        ID = p.ID,
                        Name = p.Name,
                        productImage = p.productImageByteArray,
                        Price = p.Price
                    };


                    shvm.New.Add(model);
                }

                foreach (var p in randomProducts)
                {
                    var model = new randomProducts
                    {
                        ID = p.ID,
                        Name = p.Name,
                        productImage = p.productImageByteArray,
                        Price = p.Price
                    };


                    shvm.Random.Add(model);
                }

                foreach (var p in topProducts)
                {
                    var model = new topProducts
                    {
                        ID = p.ID,
                        Name = p.Name,
                        productImage = p.productImageByteArray,
                        Price = p.Price
                    };


                    shvm.Top.Add(model);
                }


                foreach (var product in featuredProducts)
                {
                    var productViewModel = new featuredProducts
                    {
                        ID = product.ID,
                        Name = product.Name,
                        Price = product.Price,
                        Quantity = product.Quantity,
                        Description = product.Description,
                        Category = product.Category,
                        productImage = product.productImageByteArray,
                        SoldQuantity = product.QuantitySold,
                        remainingQuantity = product.Quantity - product.QuantitySold,
                        ColorSizes = product.ColorSizes.Where(cs => cs.QuantityLeft > 1).ToList()

                    };

                    shvm.Featured.Add(productViewModel);
                }
            }
            catch (Exception e)
            {
               _logger.LogError("Error Setting up Shop Index Page:"+e);
            }
          

            return View(shvm);
        }

        public async Task<IActionResult> Category(string category)
        {
     
            if (string.IsNullOrEmpty(category))
            {
                return RedirectToAction("Index");
            }
            try
            {
                var response = await _productRepo.GetAllInCategory(category);

                var productsInCategory = new List<DisplayProductViewModel>();

                foreach(var product in response)
                {
                    var productViewModel = new DisplayProductViewModel
                    {
                        ID = product.ID,
                        Name = product.Name,
                        Price = product.Price,
                        Quantity = product.Quantity,
                        Description = product.Description,
                        Category = product.Category,
                        productImage = product.productImageByteArray,
                        SoldQuantity = product.QuantitySold,
                        remainingQuantity = product.Quantity - product.QuantitySold
                    };

                    productsInCategory.Add(productViewModel);
                }

                return View(productsInCategory);

            }
            catch (Exception ex)
            {
                _logger.LogError("Error", ex.ToString());
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            try
            {
                var product = await _productRepo.FindById(id);

                var csAvaliable = product.ColorSizes.Where(cs => cs.QuantityLeft > 1).ToList();

                var productViewModel = new DisplayProductViewModel
                {
                    ID = product.ID,
                    Name = product.Name,
                    Price = product.Price,
                    Quantity = product.Quantity,
                    Description = product.Description,
                    Category = product.Category,
                    productImage = product.productImageByteArray,
                    SoldQuantity = product.QuantitySold,
                    remainingQuantity = product.Quantity - product.QuantitySold,
                    ColorSizes = csAvaliable
                };




                return View(productViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError("Error", ex.ToString());
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            try
            {
                //first check if this session has a session key
                if (_httpContextAccessor.HttpContext.Session.Get(CartSessionKey) == null)
                {
                    //if user is logged in, use username as session key
                    if (!string.IsNullOrWhiteSpace(_httpContextAccessor.HttpContext.User.Identity.Name))
                    {
                        Session.SetString(CartSessionKey, _httpContextAccessor.HttpContext.User.Identity.Name);
                    }
                    else //use a new random guid as the session key
                    {
                        var tempCartId = Guid.NewGuid();
                        Session.SetString(CartSessionKey, tempCartId.ToString());
                    }
                }
                //done checking if session has a session key, and setting one if one does not exist

                var cart = await _cartRepo.FindById(Session.GetString(CartSessionKey));
                var displayCart = new CartViewModel();

                if (cart == null)
                {

                    return View(displayCart);
                }
                displayCart.Quantity = TotalQuantity(cart.cartItems);
                displayCart.totalCost = CartCost(cart.cartItems);

                foreach (var t in cart.cartItems)
                {
                    t.Amount = t.ProductQuantity * t.ProductPrice;
                    displayCart.cartItems.Add(t);
                }

                ViewBag.Amount = displayCart.totalCost * 100;
                ViewBag.reference = Guid.NewGuid().ToString();
                ViewBag.key = "pk_live_7d721ad5edba7f71940b5658be9be93a5f549a02";

                return View(displayCart);
            }
            catch (Exception e)
            {
                _logger.LogError("Error with cart"+e);
                return View(null);
            }
            //await CartTable();
            //return View();
        }

        [HttpGet]
        public async Task<IActionResult> CartTable()
        {
            //first check if this session has a session key
            if (_httpContextAccessor.HttpContext.Session.Get(CartSessionKey) == null)
            {
                //if user is logged in, use username as session key
                if (!string.IsNullOrWhiteSpace(_httpContextAccessor.HttpContext.User.Identity.Name))
                {

src/JamRockApplication_v1/Views/Shared/NotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/JamRockApplication_v1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="57x57" href="~/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="~/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/icons/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">   
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Ticket Fort">
    <meta name="msapplication-TileColor" content="#5cb95c">
    <meta name="msapplication-TileImage" content="~/img/icons/mstile-144x144.png">
    <link rel="manifest" href="~/images/icons/manifest.json">

    <meta name="description" content="">
    <title>@ViewData["Title"]</title>
    <style>
        .viewMain {
            background: url("https://jamrock.azureedge.net/images/e3.jpg")no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            height: 100%;
        }
        .navbar {
            background-color:transparent;
        }

        .top-nav-collapse {
            background-color: #153535;
            opacity: 0.9;
            filter: alpha(opacity=90);
        }

    </style>

    <environment names="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/mdb.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/mdb.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    </environment>
</head>
<body>
    <nav class="navbar navbar-toggleable-md fixed-top navbar-dark bg-faded scrolling-navbar">
        <div class="container">

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand waves-effect waves-light" asp-controller="Home" asp-action="Index">
                <img src="https://jamrock.azureedge.net/images/brand-logo.png" alt="jamrock brand logo"/>
            </a>

            <div class="collapse navbar-collapse transparent" id="navbarNav1">

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#about">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#feeds">Feeds</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#sponsors">Sponsors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contact</a>
                    </li>
                </ul>

                <ul class="navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Blog" asp-action="Index">News</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Festivals">Festivals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Shop" asp-action="Index">Shop</a>
                    </li>
                </ul>

            </div>

        </div>

    </nav>
    @RenderBody()
    <!--Footer-->
    <footer class="page-footer center-on-small-only">

        <!--Footer Links-->
        <div class="container-fluid">
            <div class="row">

                <!--First column-->
                <div class="col-md-3 offset-lg-1 hidden-lg-down">
                    <img src="https://jamrock.azureedge.net/images/brand-logo.png" />
                </div>
                <!--/.First column-->

                <hr class="hidden-md-up">

                <!--Second column-->
                <div class="col-lg-2 col-md-4 offset-lg-1">
                    <h5 class="title">Get In Touch</h5>
                    <ul>
                        <li><a href="#!">The Secret Garden, </a></li>
                        <li><a href="#!">Riverplate park,</a></li>
                        <li><a href="#!">off Ahmadu Bello Way, </a></li>
                        <li><a href="#!">Wuse 2, Abuja FCT,Nigeria</a></li>
                    </ul>
                </div>
                <!--/.Second column-->

                <hr class="hidden-md-up">
            </div>
        </div>
        <!--/.Footer Links-->

        <hr>

        <!--Social buttons-->
        <div class="social-section">
            <ul>
                <li><a class="btn-floating btn-small btn-fb" href="https://www.facebook.com/jamrockng/"><i class="fa fa-facebook"> </i></a></li>
                <li><a class="btn-floating btn-small btn-tw" href="https://twitter.com/jamrock_ng"><i class="fa fa-twitter"> </i></a></li>
                <li><a class="btn-floating btn-small btn-ins" href="https://www.instagram.com/jamrock_ng/"><i class="fa fa-instagram"> </i></a></li>
            </ul>
        </div>
        <!--/.Social buttons-->
        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2017 Copyright: <a> JAMROCK </a>

            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    <environment names="Development">
        <script src="~/js/jquery-3.1.1.js"></script>
        <script src="~/js/tether.js"></script>
        <script src="~/js/bootstrap.js"></script>
        <script src="~/js/mdb.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script>
            new WOW().init();
            //toastr.options = {
            //    "debug": false,
            //    "positionClass": "toast-bottom-full-width",
            //    "fadeIn": 5000,
            //    "fadeOut": 5000,
            //    "timeOut": 20000,
            //    "progressBar": true,
            //    "closeButton": true
            //}
            //toastr.info("Hardcopy 5k Regular Tickets Available At The Secret Garden, Jabi Lake Mall, Legend, Adnar Robati Luxury.");

        </script>

        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBXFMI71QkTcrDE5zB53hNkv0GPJf5_lW4&callback=init_map"
                async defer></script>
        <script src="https://js.paystack.co/v1/inline.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/jquery-3.1.1.js"></script>
        <script src="~/js/tether.js"></script>
        <script src="~/js/bootstrap.js"></script>
        <script src="~/js/mdb.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script>
            new WOW().init();
        </script>

        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBXFMI71QkTcrDE5zB53hNkv0GPJf5_lW4&callback=init_map"
                async defer></script>
        <script src="https://js.paystack.co/v1/inline.js"></script>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-106410647-1', 'auto');
            ga('send', 'pageview');

        </script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/JamRockApplication_v1/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="apple-touch-icon" sizes="57x57" href="~/images/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="~/images/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="~/images/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="~/images/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="~/images/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="~/images/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="~/images/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="~/images/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="~/images/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="~/images/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/images/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="~/images/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/icons/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Ticket Fort">
    <meta name="msapplication-TileColor" content="#5cb95c">
    <meta name="msapplication-TileImage" content="~/img/icons/mstile-144x144.png">
    <link rel="manifest" href="~/images/icons/manifest.json">

    <meta name="description" content="">
    <title>Control Panel</title>

    <!-- Bootstrap core CSS     -->
    <link href="~/bootstrap3/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <!--  Material Dashboard CSS    -->
    <link href="~/css/material-dashboard.css" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link rel="stylesheet" href="~/css/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.css"/>



</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="purple">

            <div class="logo">
                <a href="#" class="simple-text">
                    Control Panel
                </a>
            </div>
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="active">
                        <a asp-controller="Admin" asp-action="Index">
                            <i class="fa fa-tachometer" aria-hidden="true"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Product" asp-action="Products">
                            <i class="fa fa-list" aria-hidden="true"></i>
                            <p>Manage All Products</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Product" asp-action="Orders">
                            <i class="fa fa-shopping-basket" aria-hidden="true"></i>
                            <p>View All Orders</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Event" asp-action="Index">
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                            <p>Manage All Events</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Users" asp-action="Customers">
                            <i class="fa fa-users" aria-hidden="true"></i>
                            <p>View All Customers</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Blog" asp-action="Posts">
                            <i class="fa fa-newspaper-o" aria-hidden="true"></i>
                            <p>Manage Blog</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Users" asp-action="NewUser">
                            <i class="fa fa-user-plus" aria-hidden="true"></i>
                            <p>Create New User</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Admin" asp-action="Documentation">
                            <i class="fa fa-book" aria-hidden="true"></i>
                            <p>How To Use</p>
                        </a>
                    </li>
                    <li>
                      <hr/>
                    </li>
                    <li>
                        <a asp-controller="Shop" asp-action="Index">
                            <i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
                            <p>Back to Shop</p>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Index">
                            <i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
                            <p>Back to HomePage</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="nav navbar-left">
                        @await Html.PartialAsync("_LoginPartial")
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">                
                    @RenderBody()
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <p class="copyright pull-right">
                        &copy;
                        <script>document.write(new Date().getFullYear())</script> <a href="http://www.heuristix.com">Managed by Heuristix</a>
                    </p>
                </div>
            </footer>
        </div>

    </div>
    
<script src="~/js/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="~/bootstrap3/bootstrap.min.js" type="text/javascript"></script>
<script src="~/js/modernizr-custom.js"></script>
<script src="~/js/site.js"></script>
    <script src="~/js/plugins/bootstrap-datepicker.min.js"></script>
    <script src="~/js/material-dashboard.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script>

    $("#dataTable").DataTable();
    $(function () {
        if (!Modernizr.inputtypes.date) {
            $('input[type=date]').datepicker({
                dateFormat: 'yy-mm-dd'
            }
            );
        }
    });
    //$('input[type=date]').datepicker({ dateFormat: 'yy-mm-dd' });

</script>

    @RenderSection("scripts", required: false)
</body>
</html>